services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./apps/api/.env.docker.local
    expose:
      - "3000"
    restart: always

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always