RAG_EMBEDDING_MODEL = "text-embedding-3-small"
RAG_EMBEDDING_DIMENSIONS = 1536
RAG_MIN_SIMILARITY = 0.45

RAG_SEARCH_TOOL_NAME = "search_rag_documents"

DEFAULT_SEARCH_LIMIT = 5
MAX_SEARCH_LIMIT = 10
SEARCH_CANDIDATE_MULTIPLIER = 4
MAX_PREFERRED_CHUNKS_PER_DOCUMENT = 2
RRF_K = 60

DEFAULT_DOCUMENT_LIST_LIMIT = 20

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

MAX_UPLOAD_SIZE = 5 * 1024 * 1024

PROCESSING_STALE_AFTER_SECONDS = 5 * 60
PROCESSING_RECOVERY_BATCH_SIZE = 100

RECOVERY_INTERVAL_SECONDS = 60
RECOVERY_LOCK_TTL_MS = 5 * 60 * 1000
RECOVERY_LOCK_KEY = (
    "lock:chat-ai-agent:rag-processing-recovery"
)

RAG_ANSWER_CONTEXT_TOKEN_BUDGET = 3000
UNKNOWN_CHUNK_TOKEN_COST = 1000
RAG_ANSWER_TIMEOUT_SECONDS = 45